# 基础镜像
FROM openjdk:8-jdk-alpine

# 指定工作目录
WORKDIR /app

# 将 jar 包添加到工作目录，比如 target/yuoj-backend-user-service-0.0.1-SNAPSHOT.jar
ADD target/service-acl-1.0-SNAPSHOT.jar .

# 暴露端口
EXPOSE 23103

# 启动命令
ENTRYPOINT ["java","-jar","-Xmx64m","-Xms64m","service-acl-1.0-SNAPSHOT.jar","--spring.profiles.active=prod"]
